import {
  Home,
  Clock,
  MessageSquare,
  FileText,
  Users,
  BarChart3,
  Settings,
  LifeBuoy,
  CreditCard,
  Briefcase,
  Star,
  Award,
  Mail,
} from "lucide-react"

export const operatorNavItems = [
  { href: "/dashboard/operator", icon: Home, label: "Dashboard" },
  { href: "/dashboard/operator/availability", icon: Clock, label: "Disponibilità" },
  { href: "/dashboard/operator/platform-messages", icon: MessageSquare, label: "Messaggi" },
  { href: "/dashboard/operator/consultations-history", icon: FileText, label: "Consulti" },
  { href: "/dashboard/operator/client-notes", icon: Users, label: "Note Clienti" },
  { href: "/dashboard/operator/earnings", icon: BarChart3, label: "Guadagni" },
  { href: "/dashboard/operator/payouts", icon: CreditCard, label: "Pagamenti" },
  { href: "/dashboard/operator/services", icon: Briefcase, label: "Servizi" },
  { href: "/dashboard/operator/reviews", icon: Star, label: "Recensioni" },
  { href: "/dashboard/operator/gamification", icon: Award, label: "Gamification" },
  { href: "/dashboard/operator/commission-request", icon: Mail, label: "Richiesta Provvigione" },
  { href: "/profile/operator", icon: Settings, label: "Impostazioni Profilo" },
  { href: "/support", icon: LifeBuoy, label: "Supporto" },
]
