-- Step 1: Create the missing 'logs' table
CREATE TABLE IF NOT EXISTS public.logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    level text,
    message text,
    context jsonb
);
COMMENT ON TABLE public.logs IS 'Table for application-level logging.';

-- Step 2: Fix the user profile creation trigger
-- This function runs when a new user signs up in Supabase Auth.
-- It creates a corresponding entry in our public 'profiles' table.
-- This version is more robust and ensures all necessary fields are handled.

-- Drop the existing function and trigger if they exist, to start fresh
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
DROP FUNCTION IF EXISTS public.handle_new_user;

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER SET search_path = public
AS $$
BEGIN
  -- Insert a new profile row for the new user.
  -- It pulls the full_name from the metadata provided during sign-up.
  -- It sets the default role to 'client'.
  INSERT INTO public.profiles (id, full_name, email, role)
  VALUES (
    new.id,
    new.raw_user_meta_data->>'full_name',
    new.email,
    'client' -- All new users start as 'client' by default
  );
  RETURN new;
END;
$$;

-- Create the trigger that executes the function after a new user is created in auth.users
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- Log the successful fix
INSERT INTO public.logs (level, message, context)
VALUES ('info', 'Fixed schema: created logs table and updated handle_new_user trigger.', '{"script": "018-fix-schema-and-trigger.sql"}');
